name: test
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: latest

  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu
          - windows
          - macos

    name: "${{ matrix.platform }}"

    runs-on: ${{ matrix.platform }}-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest
      - name: Format check
        run: gofumpt -l .

      - name: Go test
        run: go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: false
